### ISSUE TITLE
Crash on input "一人です"

### ISSUE THREAD

**Issue by tmfink** [Yasu-umi/sudachiclone-rs#8]
Program crashes with input `一人です`.

```
$ RUST_BACKTRACE=1 cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/sudachiclone`
一人です         
thread 'main' panicked at 'index 5 out of range for slice of length 4', src/plugin/default_input_text_plugin.rs:52:30
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2751
  14: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libcore/slice/mod.rs:2919
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libcore/slice/mod.rs:2732
  16: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/vec.rs:1942
  17: <sudachiclone::plugin::default_input_text_plugin::DefaultInputTextPlugin as sudachiclone::plugin::input_text_plugin::RewriteInputText>::rewrite
             at src/plugin/default_input_text_plugin.rs:52
  18: <sudachiclone::plugin::input_text_plugin::InputTextPlugin as sudachiclone::plugin::input_text_plugin::RewriteInputText>::rewrite
             at src/plugin/input_text_plugin.rs:27
  19: <sudachiclone::tokenizer::Tokenizer as sudachiclone::tokenizer::CanTokenize>::tokenize
             at ./src/tokenizer.rs:170
  20: sudachiclone::tokenize
             at src/main.rs:51
  21: sudachiclone::main
             at src/main.rs:262
  22: std::rt::lang_start::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:67
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  25: std::panicking::try
             at src/libstd/panicking.rs:274
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  28: std::rt::lang_start
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:67
  29: main
  30: __libc_start_main
  31: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ianki** [comment]
There seems to be a bug in the max length calculation

`let max_length = min(*self.key_lengths.get(&original).unwrap_or(&0), count - 1);`

fixed to...
`let max_length = min(*self.key_lengths.get(&original).unwrap_or(&0), count - i_us);`

@Yasu-umi there are a number of bugs here and there, for example "弟は2つのスマホを使い分けている。" parsing fails in the DoubleArrayTrie.  Is there any plan to continue enhancing this project?
